### ISSUE TITLE
Inherited methods are not validated

### ISSUE THREAD

**Issue by smolchanovsky** [nclient/NClient#218] opened 2021-06-01 22:44 UTC
**Describe the bug**
Inherited methods are not validated during the creation of the client instance. The error occurs when executing an invalid method.

**To Reproduce**
```C#
public interface IMyClient : IMyController
{
}

public interface IMyController
{
    [GetMethod("{non_existent_parameter}")]
    int[] Get();
}

...

var client = NClientGallery.Clients.GetRest()
    .For<IMyClient>(host: "http://localhost:5000")
    .Build();
```

**Expected behavior**
I expect the exception to be thrown when calling the `Use<>` method.

**Project info:**
 - Version NClient - 0.5.1

**Comment by VictorLlanir** [comment] 2022-06-19 13:42
Hello, @smolchanovsky, I would like to work no this issue. Could you assign it to me?

**Comment by smolchanovsky** [comment] 2022-06-19 21:06
Hi, @VictorLlanir! Sure :)
If you have any difficulties, write here, I will be glad to help

**Comment by smolchanovsky** [comment] 2022-07-08 15:21
Hello, @VictorLlanir ! Are you having difficulty fixing this bug? Or have you changed your mind and decided not to deal with the issue?

**Comment by reaver330** [comment] 2022-08-22 12:59
Hi @smolchanovsky it looks like Victor isn't going to progress this issue? If not I'd like to grab it. Is there a failing test for this bug already? I noticed you have a bewilderingly large number of tests: where would you like me to put the tests for this bug?

**Comment by reaver330** [comment] 2022-08-23 05:19
Ok great, thank you. I tend to use _given_when_then_ when naming my tests but it looks like you're using something else, I'd like to stick to whatever your naming scheme is. Have you got a link or something that explains the approach? Also I don't use Resharper, but I'll include the suppression attribute anyway. I assume your using dotCover for code coverage metrics? I'm cheap and I use openCover :D (I'll exclude anything i do with openCover from the commits).

**Comment by smolchanovsky** [comment] 2022-08-23 09:43
Most tests use `UnitOfWork_StateUnderTest_ExpectedBehavior` naming ([link](https://methodpoet.com/unit-test-method-naming-convention/)). The [AAA pattern](https://freecontent.manning.com/making-better-unit-tests-part-1-the-aaa-pattern/) is also used. dotCover is not used :) Test coverage metrics are collected using [opencover and Sonarcloud](https://github.com/nclient/NClient/blob/main/.github/workflows/sonarcloud-analysis.yml).

Thanks for the questions, I will add information about this in the Contributor's Guide

**Comment by reaver330** [comment] 2022-08-23 12:00
Ok cool I'll use the same naming for the tests and the AAA pattern, thanks for sharing @smolchanovsky. In terms of the expected behavior do you want the exceptions to be thrown by the clientValidator on `.Build()` or do you want them thrown on `.use<>` like it was set out in the original Expected Behavior above. (If use<> which use<>... I see there's a few like `NClientTransportResponseMappingSetter.Use`, `INClientFactoryResilienceMethodSelector.Use` etc?)

**Comment by smolchanovsky** [comment] 2022-08-23 13:41
`Use<>` method from the original issue description no longer exists :)
Conceptually, validation should take place in [`Build` method](https://github.com/nclient/NClient/blob/9debf7d46b5d434195bc79f09d965eb61116a5de/src/NClient/NClient.Standalone/ClientProxy/Building/NClientOptionalBuilder.cs#L171), because only in this point the builder has the entire context about the client to make a decision about the client's validity. So, an exception should be thrown in `Build` method. Now validation is already going on in this method, but exceptions are not thrown - this is a bug in validator. Based on this, you can abstract from other classes and make edits only in [`ClientValidator`](https://github.com/nclient/NClient/blob/main/src/NClient/NClient.Standalone/ClientProxy/Validation/ClientValidator.cs).

By the way, we can refactor the validation a bit. As additional **optional** fixes:

- It would be nice to change the logic of creating a ClientValidator. Now it is created at [each time](https://github.com/nclient/NClient/blob/9debf7d46b5d434195bc79f09d965eb61116a5de/src/NClient/NClient.Standalone/ClientProxy/Building/NClientOptionalBuilder.cs#L174) the `Build` method is called, this is redundant. It would be possible to create it in `NClientOptionalBuilder` constructor and use this instance for a building.

- [`EnsureAsync` method](https://github.com/nclient/NClient/blob/9debf7d46b5d434195bc79f09d965eb61116a5de/src/NClient/NClient.Standalone/ClientProxy/Validation/ClientValidator.cs#L57) should not accept `IClientInterceptorFactory`. It is better to pass it to the constructor and then use it in this method.

**Comment by reaver330** [comment] 2022-08-24 13:29
Hi @smolchanovsky, 

Looking over the validation code [EnsureValidityAsync](https://github.com/nclient/NClient/blob/89b7b0a12371eb11da78bae465b624f8d60527e2/src/NClient/NClient.Standalone/ClientProxy/Validation/ClientValidator.cs#L66) it looks like it doesn't apply any of the checks that are performed in `RouteProvider.Build` - which calls `GetRouteParameter` which then throws the `ClientValidationException` of _"The token 'missing_get_parameter' in route template does not match any method parameters."_. 

The `ClientValidator` really only seems to check if the [methods exist on the type](https://github.com/nclient/NClient/blob/89b7b0a12371eb11da78bae465b624f8d60527e2/src/NClient/NClient.Standalone/ClientProxy/Validation/ClientValidator.cs#L68) and can be invoked. I notice that it also doesn't check for interface methods: in your example above `IMyClient` has no member methods and so `ClientValidator` doesnt check the interface `IMyController` for any methods. I'm thinking along these lines currently:
``` C# 
if(typeof(T).GetMethods().Length == 0)
{
    Type[] interfaces = typeof(T).GetInterfaces();
    foreach( Type iface in interfaces)
    {
        //This will only occur for client interfaces that have no methods themselves 
        //but do implement an interface that does have methods.
        //This doesn't recurse to interfaces on the interfaces on the client interface. 
        //Do you foresee that this recursion of implemented interfaces would be needed?
        //Then would validate the methods can be invoked as per normal
    }
}
else
{
    //this will only occur for client interfaces that have methods on them
    //validate the methods can be invoked as per normal
}
```
I don't want to re-write all the validation logic that is already sprinkled throughout `RouteProvider.Build` like [here](https://github.com/nclient/NClient/blob/8cc5e45972f657a9f005557a85ee366289ccc4f4/src/NClient.Providers/NClient.Providers.Api.Rest/Providers/RouteProvider.cs#L55) and [here](https://github.com/nclient/NClient/blob/8cc5e45972f657a9f005557a85ee366289ccc4f4/src/NClient.Providers/NClient.Providers.Api.Rest/Providers/RouteProvider.cs#L71) because it feels like a waste, and calling `RouteProvider.Build` twice, once for validation and once when executing the actual request also seems wasteful, and potentially slow.

So after this long story :) i really wanted to check with you how you would like this fixed, maybe by simply checking the route parameters are there? Or if you want all the validation logic that `RouteProvider.Build` applies, to also be applied in `ClientValidator`? Or something else maybe? I will also extend `ClientValidator.EnsureValidityAsync` to also check interfaces that are implemented, as outlined above, if you think this is a good idea.

> It would be nice to change the logic of creating a ClientValidator. Now it is created at [each time](https://github.com/nclient/NClient/blob/9debf7d46b5d434195bc79f09d965eb61116a5de/src/NClient/NClient.Standalone/ClientProxy/Building/NClientOptionalBuilder.cs#L174) the Build method is called, this is redundant. It would be possible to create it in NClientOptionalBuilder constructor and use this instance for a building.

>[EnsureAsync method](https://github.com/nclient/NClient/blob/9debf7d46b5d434195bc79f09d965eb61116a5de/src/NClient/NClient.Standalone/ClientProxy/Validation/ClientValidator.cs#L57) should not accept IClientInterceptorFactory. It is better to pass it to the constructor and then use it in this method.

I have corrected these two, they were very minor. They will be included in this fix's PR.

**Comment by smolchanovsky** [comment] 2022-08-24 16:15
Hi @reaver330! You did a great research, thank you!

I see three problems now:
1. Validator does not check all methods of the client interface
2. Validator incorrectly checks the methods
3. Validator does not handle `TargetInvocationException`

What solutions can I offer:

1. The first problem is fixed easily enough. You can do as you suggested, but it's better to use the extension method, which allows you to get all the interface methods (including inherited ones) - [`NClient.Core.Helpers.TypeExtensions.GetInterfaceMethods`](https://github.com/nclient/NClient/blob/9debf7d46b5d434195bc79f09d965eb61116a5de/src/NClient/NClient.Core/Helpers/TypeExtensions.cs#L45)

2. The second problem is more complicated. First, let's determine which client interface is valid for us. I think the client is valid if it is possible to create a request. Therefore, we need to execute all client methods skipping all steps except creating a request (IRequestBuilderProvider is responsible for this). Then you can solve the problem as follows: the builder must pass the `BuilderContext<TRequest, TResponse>` to `EnsureAsync` method, then all steps that are not important for validation will be removed from `BuilderContext`, after which the modified `BuilderContext` can be used for validation. It can be done something like this:
```C#
public async Task EnsureAsync<TClient, TRequest, TResponse>(
            IClientInterceptorFactory clientInterceptorFactory, 
            BuilderContext<TRequest, TResponse> builderContext)
            where TClient : class
        {
            var validationContext = builderContext
                .WithHost(FakeHost)
                .WithTransport(
                    new StubTransportProvider<TRequest, TResponse>(),
                    new StubTransportRequestBuilderProvider<TRequest, TResponse>(),
                    new StubResponseBuilderProvider<TRequest, TResponse>())
                .WithSerializer(new StubSerializerProvider())
                .WithoutAuthorization()
                .WithoutHandlers()
                .WithoutResiliencePolicy()
                .WithoutAllResponseMapperProviders()
                .WithoutResponseValidation()
                .WithoutLogging();
            
            var interceptor = clientInterceptorFactory.Create<TClient, TRequest, TResponse>(validationContext);
            ...
        }
```
Changing the BuilderContext inside the validator will not cause an error, since it is immutable. You will also need to make `StubTransportProvider', `StubTransportRequestBuilderProvider' and `StubResponseBuilderProvider` generics. They can do nothing and simply return `default`

3. The third problem is solved by checking `InnerException`, it should have `ClientValidationException`. The other exceptions should be ignored

Due to the many changes that have occurred, the Issue turned out to be more complicated than at the time of its creation 😅

> calling RouteProvider.Build twice, once for validation and once when executing the actual request also seems wasteful, and potentially slow

The overhead of this is not a problem, since the client must be a singleton (including due to [problems in HttpClient](https://docs.microsoft.com/en-us/dotnet/fundamentals/networking/httpclient-guidelines#recommended-use)), so validation will occur once to launch the application. In the future, I want to make validation optional and give the opportunity to use the validator in tests

**Comment by reaver330** [comment] 2022-08-25 13:52
Hi @smolchanovsky, 

>Due to the many changes that have occurred, the Issue turned out to be more complicated than at the time of its creation 😅

I have been coding for 20 years but i took a break about 4 years ago and so I was looking for some small and simple issues that i could contribute to so i can refresh my skills again. It would seem that i am destined for a lot more than just simple issues 😂 but I must admit to having a huge amount of fun with this code-base. I have not often had the opportunity to work with such a large framework that makes such extensive use of generics and reflection. I have not used generics so rigorously before so please forgive me if there are some things that i don't quite understand yet.

>Changing the BuilderContext inside the validator will not cause an error, since it is immutable. You will also need to make StubTransportProvider', StubTransportRequestBuilderProvider' and StubResponseBuilderProvider generics. They can do nothing and simply return default

Making these three Stubs generics looked simple on the surface, however when i dug deeper into the code I realised that this chain of interactions could potentially introduce large changes and I wanted to run them past you first:

`StubTransportProvider<TRequest, TResponse>.Create` returns a `StubTransport<IRequest, IResponse>` which implements `ITransport<IRequest, IResponse>`  
**<IRequest, IResponse>** these interfaces are of course not generic types and switching ITransport to use <TRequest, TResponse> causes `StubTransport.ExecuteAsync` to break because it returns a `Response: Response, IResponse` and switching Response's ctor to use TResponse instead of IResponse broke a lot of things. 

I am hoping that I somehow have made some mistake with the generics and this large number of changes isn't required. I looked over the other generic implementations like [StubClientHandler](https://github.com/nclient/NClient/blob/01dc161fa614d04271e0ce9af1e2caeb62072d20/src/NClient/NClient.Standalone/ClientProxy/Validation/Handling/StubClientHandler.cs#L7) and [StubResiliencePolicyProvider](https://github.com/nclient/NClient/blob/14466c2654afeb855686eccd1ac049041d9fce06/src/NClient/NClient.Standalone/ClientProxy/Validation/Resilience/StubResiliencePolicyProvider.cs#L6) and the interfaces always have the generic types on them and not the IRequest/IResponse interfaces. However `Request` implements IRequest and switching it to use the generic TRequest causes havok because Response: IResponse uses IResponse all over the class, and its very large and looks like its used extensively throughout the framework. 

So once again I have told a long story, but I didn't want to rush off and try to convert an important part of the framework (`Request: IRequest`) to be generic simply because `StubTransportProvider` depends on it. 

Like I mentioned before I think there is some error in my understanding and there is some way to apply the generic params without them filtering down to `Request: IRequest`. 

>You will also need to make StubTransportProvider', StubTransportRequestBuilderProvider' and StubResponseBuilderProvider generics.

Is this change too large for now perhaps? Or do I misunderstand and somehow this change is simple?

**Comment by smolchanovsky** [comment] 2022-08-25 16:36
To begin with, I will try to explain what the transport level is. NClient has additional abstractions: `IRequest` and `IResponse'. Along with request metadata, they also store data and errors as deserialized objects. The transport layer accepts the abstraction `IRequest`, executes HTTP request and returns `IResponse'. However, internally, the transport layer uses `TRequest` and `TResponse` to make requests, which are generally HttpClient messages.

Now back to validation. In validation, we are only interested in what happens before sending a request to the transport layer - creating a request. The easiest (but not the best) way to check the client for validity is to try to send a request to a fake host. Thus, we need to make the stub transport layer is as generic as possible and does nothing.

So the changes should affect only 6 classes that are in this [folder](https://github.com/nclient/NClient/tree/main/src/NClient/NClient.Standalone/ClientProxy/Validation/Transport), and changes will be quite simple: each class should be generic and use generic parameters (`TRequest` and `TResponse`) instead of specific `IRequest` and `IResponse`. Please note that not all `IRequest` and `IResponse` need to be replaced, but only generic parameters. Because the interfaces have both. I explained why this is so at the beginning of my message. It probably sounds confusing, so I'll show you an example:
```C#
internal class StubResponseBuilder<TRequest, TResponse> : IResponseBuilder<TRequest, TResponse>
{
    public Task<IResponse> BuildAsync(IRequest request, 
        IResponseContext<TRequest, TResponse> responseContext, bool allocateMemoryForContent, CancellationToken cancellationToken)
    {
        return Task.FromResult<IResponse>(default!);
    }
}
```
Here, the class still accepts `IRequest` and returns `IResponse`, since the interface requires it. 
```
public interface IResponseBuilder<TRequest, TResponse>
{
    Task<IResponse> BuildAsync(IRequest request, 
        IResponseContext<TRequest, TResponse> responseContext, bool allocateMemoryForContent, CancellationToken cancellationToken);
}
```
It turns out that if we follow the interface contract and do not change it, then the changes will affect only six stub classes

**Comment by reaver330** [comment] 2022-08-29 12:59
Hi @smolchanovsky 

Ok so things have been going ok so far, but now there is an interesting difficulty: `StubResponseBuilder` returns `ResponseContext.Response` from [here](https://github.com/nclient/NClient/blob/df406421f943b6f2e2706cbdce1dd2f849671d34/src/NClient/NClient.Standalone/ClientProxy/Validation/Transport/StubResponseBuilder.cs#L13)

The problem with this, is when performing validation the StubResponseBuilder returns a response with a null `Response.Content.Stream` property.  This means that  `TryGetDataObject` from [here ](https://github.com/nclient/NClient/blob/c67ab29220233f8423b43b29cc0d34152fb9dab8/src/NClient/NClient.Standalone/Client/TransportNClient.cs#L300) returns `null` (for the empty Content Stream). This `null` flows upward until `ExecuteHttpResponseAsync` from [here](https://github.com/nclient/NClient/blob/89b7b0a12371eb11da78bae465b624f8d60527e2/src/NClient/NClient.Standalone/ClientProxy/Generation/Interceptors/ClientInterceptor.cs#L132) returns the null and then `ProcessInvocationAsync` from [here](https://github.com/nclient/NClient/blob/89b7b0a12371eb11da78bae465b624f8d60527e2/src/NClient/NClient.Standalone/ClientProxy/Generation/Interceptors/ClientInterceptor.cs#L80) fails with a _System.NullReferenceException : Object reference not set to an instance of an object._

```C#
protected override async Task<TResult> InterceptAsync<TResult>
```
This could be changed to allow nullable <TResult> return values, but before i consider this I wanted to check with you first...

**Comment by smolchanovsky** [comment] 2022-08-29 13:38
Hello, @reaver330! Thanks for the question :)

The exception is fine, we do not check the entire pipeline of request execution, we are only interested in creating a request (`IRequest`). What happens next, it no longer matters for validation. When the pipeline reaches `StubTransportRequestBuilderProvider` class, it means that `IRequest` has already been created and the client interface is valid. Therefore, all classes that are used further are made stabs that do nothing or throw exceptions.

Alternatively, you can terminate the pipeline execution when the request has already been created. In this case, I suggest to create internal exception, for example `ValidationSuccessfulFinishedException` (heh, oxymoron) and always throw it in `StubTransportRequestBuilderProvider` and catch it in the `EnsureValidityAsync` method. This is even better, because we are not doing unnecessary work and we can be sure that the validation was successful and no unexpected exceptions were thrown.

Then you will have the following solution:
```
try
{
    var result = methodInfo.Invoke(client, parameters);
    if (result is Task task)
        await task.ConfigureAwait(false);
}
catch (ClientValidationException)     // <- If this exception is received, then the validation was failed
{
    throw;
}
catch (ValidationSuccessfulFinishedException)    // <- If this exception is received, then the validation was successful
{
    // ignored
}
```

**Comment by reaver330** [comment] 2022-08-30 08:55
Hi @smolchanovsky 

I am concerned that using an exception for managing program control flow is an anti-pattern. Microsoft are clear on their page on [C# Exceptions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/creating-and-throwing-exceptions): _Don't use exceptions to change the flow of a program as part of ordinary execution. Use exceptions to report and handle error conditions._ 
This is your project though so if you insist i will use the 'successfulException' method above.

What about using the IToolset interface to terminate the current execution of the pipeline? Something like this:
```C#

public interface IToolset
{
    ISerializer Serializer { get; }

    ILogger Logger { get; }

    bool HaltPipelineExecution { get; set; }
}

internal class StubTransportRequestBuilderProvider<TRequest, TResponse> : ITransportRequestBuilderProvider<IRequest, IResponse>
{
    public ITransportRequestBuilder<IRequest, IResponse> Create(IToolset toolset)
    {
        toolset.HaltPipelineExecution = true;
        return new StubTransportRequestBuilder<TRequest, TResponse>();
    }
}

private async Task<object?> ProcessInvocationAsync(IInvocation invocation, Type resultType)
{
  ...
  var transportNClient = _transportNClientFactory.Create();
  if (_toolset.HaltPipelineExecution)
  {
     //return a non-null so the pipeline can exit gracefully
  }
  else
  {
    cont...
  }
}
```

**Comment by smolchanovsky** [comment] 2022-08-30 09:21
Hey, @reaver330!

You're absolutely right about the antipattern. I suggested this solution as a tradeoff: it won't make it worse than it is now and it's easy to implement. If you are ready to offer or consider more complex options, you will have all my support :)

I would not like to use `IToolset` to halt pipeline execution, since it has other responsibility. `IToolset` is a set of helpers that may be needed to implement providers that extend functionality of the client

**Comment by reaver330** [comment] 2022-08-30 13:06
Hi @smolchanovsky 

Ok cool, I'd like to do this without the successException - if it becomes so complex that I have a stroke, perhaps i will eat my own words but after spending some time thinking about it; using a `CancellationToken` to gracefully exit the pipeline instead seems more appropriate, what do you think?

**Comment by smolchanovsky** [comment] 2022-08-30 13:19
@reaver330, I was thinking about cancelling via CancellationToken, I didn't consider this option because it's not very obvious logic, but it makes sense. So I will approve this solution

**Comment by reaver330** [comment] 2022-09-01 11:33
Hi @smolchanovsky 

I have nearly finished, but something has come up that I'm not sure about:

Certain tests are now throwing `ClientValidationException : The attribute 'IOperationAttribute' not found.` I think this is a valid exception as its type is `ClientValidationException` but it is affecting 528 tests. 
This exception is thrown because OperationAttributeProvider.Get [here](https://github.com/nclient/NClient/blob/b278c64fa078b5828f4081945f659a5aa73d8221/src/NClient/NClient.Standalone/ClientProxy/Generation/MethodBuilders/Providers/OperationAttributeProvider.cs#L31), performs the attribute existence check for `IOperationAttribute`. I suspect that this exception has always been thrown but the `ClientValidator` was always swallowing it.

Can you tell me a little bit more about this attribute, and why sometimes it would be missing on the tests, for exmaple:
[this one](https://github.com/nclient/NClient/blob/d37de9974ca88bdfd77fda9d5330dab04c569c6e/tests/NClient/NClient.Tests/ClientFactoryTests/ResilienceNClientFactoryTest.cs#L304)
or [this one
](https://github.com/nclient/NClient/blob/df406421f943b6f2e2706cbdce1dd2f849671d34/tests/NClient.Providers/NClient.Providers.Serialization.SystemTextJson.Tests/SystemTextJsonClientTest.cs#L40)
This is an example of the TestLog:
```
 CancellationClient_GetAsyncWithCancellation_ThrowTaskCanceledException
   Source: CancellationClientTest.cs line 60
   Duration: 136 ms

  Message: 
NClient.Exceptions.ClientValidationException : The attribute 'IOperationAttribute' not found.

  Stack Trace: 
ClientValidator`2.TraverseInnerExceptionGraph(Exception ex) line 127
<EnsureValidityAsync>d__7`1.MoveNext() line 114
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
ConfiguredTaskAwaiter.GetResult()
<EnsureAsync>d__6`1.MoveNext() line 86
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
TaskAwaiter.GetResult()
NClientOptionalBuilder`3.Build() line 178
<CancellationClient_GetAsyncWithCancellation_ThrowTaskCanceledException>d__3.MoveNext() line 66
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
GenericAdapter`1.GetResult()
AsyncToSyncAdapter.Await(Func`1 invoke)
TestMethodCommand.Execute(TestExecutionContext context)
SimpleWorkItem.PerformWork()
```

**Comment by smolchanovsky** [comment] 2022-09-01 12:38
Hey @reaver330!

The attribute is needed to specify which type of operation to use. In the case of HTTP, this is GET, POST, PUT, DELETE, etc.

Error happens in such cases:
```
interface IFoo
{
    Task Create(Entity entity);
}

interface IBar : IFoo
{
    new Task Create(Entity entity);
}
```
`IFoo` is an invalid interface as a client, but `IBar` is valid. However, despite the fact that `IBar` is valid, an exception is thrown. The error occurs because we check all methods of all interfaces (`IFoo. Create` and `IBar.Create`). In our case, we need to check only the available methods, so all methods except hidden with `new` keyword

**Comment by reaver330** [comment] 2022-09-01 13:32
Ah-ha! Thank you - do you want me to validate all the parent methods on IFoo that are _not_ hidden by the `new` keyword, or should I always skip validating the parents methods?

**Comment by smolchanovsky** [comment] 2022-09-01 13:41
Parent methods must be validated, but only those that are not hidden by the keyword `new' :)

**Comment by reaver330** [comment] 2022-09-07 11:59
Hi @smolchanovsky 

Ok so this method i was going to use but i was worried since it does not allow for the difference between these two:

```c#
public interface IMyClient: IMyController
{
    [DeleteMethod()]
    void DeleteAsync();
}

public interface IHiddenMyClient : IMyController
{
    [DeleteMethod()]
    new void DeleteAsync();
}

 public interface IMyController
{
    void DeleteAsync();
}
```

The `IMyClient` definition of `DeleteAsync` appears the same as `IHiddenMyClient.DeleteAsync` to my validation code using the example of checking method.name, method.paramTypes, method.paramCount etc , if this is ok: then I have it working. I just need to tidy up the code before submitting the PR. You will see, I write code from 2015 so I am expecting many changes after I submit :)

**Comment by smolchanovsky** [comment] 2022-09-07 12:50
Hi @reaver330!

> Ok so this method i was going to use but i was worried since it does not allow for the difference between these two:

We don't need to know about this difference, these are the same cases for us. I'll explain why. As far as I know, `new` keyword is only needed to remove the compiler warning that informs that the method has been hidden. That is why there are no differences in `MethodInfo`.

I'm looking forward to your PR :)

**Comment by reaver330** [comment] 2022-09-08 04:41
Hi @smolchanovsky 

I have all the NClient tests passing, and code coverage of the code I have added is +-87%. Do you want me to do the PR into main, or one of the other branches instead?

**Closed** 2022-12-04 09:55 UTC
Labels: Type: Bug, Good first issue, Cost: S, Priority: Medium
